---
- name: Add local pub key to authorized_keys
  authorized_key:
    user: root
    key: "{{ lookup('file', 'id_rsa.pub') }}"
    state: present

- name: Tweak sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ".*UseDNS.*"
    line: "UseDNS no"

- name: Configure GRUB to enable serial console
  copy:
    src: grub.centos
    dest: /etc/default/grub
    mode: '0644'
    owner: root
    group: root
    backup: no
  when: ansible_distribution == 'CentOS'

- name: Regenerate GRUB configuration
  command: "/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg"
  when: ansible_distribution == 'CentOS'

- name: Configure GRUB to enable serial console
  copy:
    src: grub.ubuntu
    dest: /etc/default/grub
    mode: '0644'
    owner: root
    group: root
    backup: no
  when: ansible_distribution == 'Ubuntu'

- name: Regenerate GRUB configuration
  command: "/usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg"
  when: ansible_distribution == 'Ubuntu'

- name: Install common packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"
